# BEV parameters
WIDTH = 128
HEIGHT = 128
NUMBER_OF_CHANNELS = 3
Z_SCALE = 0.2
RANDOM_MIN_VALUE = 0.0001
RANDOM_MAX_VALUE = 0.001

# Dataset parameters
BATCH_SIZE = 64
SOURCE_DIR = 'Data/dataset/sequences/00/velodyne/'

# AutoEncoder parameters
INPUT_SHAPE = (HEIGHT, WIDTH, NUMBER_OF_CHANNELS)
OUTPUT_SHAPE = (HEIGHT, WIDTH, NUMBER_OF_CHANNELS)
BOTTLENECK_NUMBER_OF_FEATURE = 128